apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simple-pod
spec:
  initContainers:
  - name: init-myservice
    image: busybox
    command:
    - sh
    - -c
    - "sleep 2; echo myservice;"
  - name: init-mydb
    image: busybox
    command:
    - sh
    - -c
    - "sleep 2; echo mydb;"
  containers:
    - name: simple-pod
      image: nginx
      ports:
      - containerPort: 80
