apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simple-pod
spec:
  containers:
  - name: simple-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: TESTENV01
      value: "testvalue01"
    - name: HOSTNAME
      # 값을 직접 할당하는 것이 아닌 참조하는 값을 설정함
      valueFrom:
        # 파드의 현재 설정 내용을 값으로 설정
        fieldRef:
          # fieldRef에서 값을 참조하려는 항목의 위치 지정
          fieldPath: spec.nodeName
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CPU_LIMIT
      valueFrom:
        # 컨테이너의 resource 정보 참조
        resourceFieldRef:
          containerName: simple-pod
          resource: limits.cpu