apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-label01
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      # label 설정
      labels:
        app: nginx
        environment: develop
        release: beta
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80