# statefulSet에서 사용할 서비스 설정
apiVersion: v1
kind: Service
# 서비스 이름과 스테이트풀세트에서 만들어진 파드 이름을 조합하면 
# 클러스터 안에서 사용하는 도메인을 만들 수 있음.
# 파드이름.서비스이름 형식
metadata:
  name: nginx-statefulset-service
  labels:
    app: nginx-statefulset-service
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-statefulset-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  # 파드 업데이트, 기본 값은 롤링 업데이트
  # OnDelete: 파드 삭제 시 변경 사항 적용
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: nginx-statefulset
  serviceName: "nginx-statefulset-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-statefulset
    spec:
      # 하던 작업을 마무리하고 정상적으로 종료할 시간
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-statefulset
        image: nginx
        ports:
        - containerPort: 80
          name: web
        env:
        - name: testenv
          value: testvalue03