apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
  annotations:
    # rollback history에서 출력되는 리비전의 주요 내용 지정
    kubernetes.io/change-cause: version 1.20.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels: 
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:1.20.1
        ports:
        - containerPort: 80